source 'https://rubygems.org'
ruby '2.3.1'

gem 'sinatra'
gem 'puma'
gem 'foreman'
gem 'redis'
gem 'msgpack'
gem 'hiredis'
gem 'feedtosis', git: 'https://github.com/alown/feedtosis'
gem 'moneta'
gem 'builder'
